## SECURITY
login:
    pattern:    /login
    defaults:   { _controller: FuentesWorksNickelTrackerBundle:Security:login }

login_check:
    pattern:    /login_check

logout:
    pattern:    /logout

## Dashboard
fuentesworks_nickeltracker_dashboard:
    pattern:    /
    defaults:   { _controller: FuentesWorksNickelTrackerBundle:Dashboard:home }